import type { Metadata } from "next";
import { Fira_Code, Geist, Geist_Mono, Inter, JetBrains_Mono, Lato, Montserrat, Roboto, Roboto_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const inter = Inter({ subsets: ['latin', "cyrillic"], display: 'swap', variable: '--font-inter' });
const roboto = Roboto({ 
  weight: ['400', '500', '700'],
  subsets: ['latin', "cyrillic"],
  display: 'swap',
  variable: '--font-roboto'
});
const robotoMono = Roboto_Mono({ 
  weight: ['400', '500', '700'],
  subsets: ['latin', 'cyrillic'],
  display: 'swap',
  variable: '--font-roboto'
});
const lato = Lato({ 
  weight: ['400', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-lato'
});
const montserrat = Montserrat({ subsets: ['latin', 'cyrillic'], display: 'swap', variable: '--font-montserrat' });
const firaCode = Fira_Code({
  weight: ['400', '500', '700'],
  subsets: ['latin', 'cyrillic'],
  display: 'swap',
  variable: '--font-fira-code'
});
const jetBrainsMono = JetBrains_Mono({
  weight: ['400', '500', '700'],
  subsets: ['latin', 'cyrillic'],
  display: 'swap',
  variable: '--font-jet-brains-mono'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable} 
          ${geistMono.variable}
          ${inter.variable}
          ${roboto.variable}
          ${robotoMono.variable}
          ${lato.variable}
          ${montserrat.variable}
          ${firaCode.variable}
          ${jetBrainsMono.variable}
          antialiased
        `}
      >
        {children}
      </body>
    </html>
  );
}
